name: Metrics Renders

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: picture/base.svg
          token: ${{ secrets.PAT_TOKEN }}
          output_action: none
          user: Pleasurecruise
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai

      - name: Mostused
        uses: lowlighter/metrics@latest
        with:
          filename: picture/mostused.svg
          token: ${{ secrets.PAT_TOKEN }}
          output_action: none
          user: Pleasurecruise
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: jupyter, html
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
      
      - name: Opened
        uses: lowlighter/metrics@latest
        with:
          filename: picture/followup.svg
          token: ${{ secrets.PAT_TOKEN }}
          output_action: none
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_archived: yes      

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: picture/calendar.svg
          token: ${{ secrets.PAT_TOKEN }}
          output_action: none
          base: ""
          plugin_calendar: yes

      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: picture/wakatime.svg
          token: NOT_NEEDED
          output_action: none
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: picture/stars.svg
          token: ${{ secrets.PAT_TOKEN }}
          output_action: none
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Commit metrics renders
        run: |
          set -e
          sudo cp -a /metrics_renders/. ./
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "chore: update metrics"
          git push
